guru:
  username: John
  password: somepass
  dburl: afdsfafd

  jms:
    username: JMS Username
    password: somepasswd
    url: SomeURL


---
spring:
  profiles: de

guru:
  jms:
    username: JMS Username $$$$$ German
